services:

  frontend:

    build: .

    container_name: tareas_frontend

    ports:
      - "8080:80"
    
    volumes:
    - .:/var/www/html

    depends_on:
      database:
        condition: service_healthy

  database:

    image: mysql:8.0

    container_name: tareas_database

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_tareas

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data: